server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update

  redis:
    host: localhost
    port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Initial
#    @see org/springframework/boot/autoconfigure/flyway/FlywayProperties.java
    locations: "classpath:db/migration"
# パラメータの値をログに表示 ex.) binding parameter [1] as [INTEGER] - [1]
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE